apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
      - db
  versions:
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - template
              properties:
                clusters:
                  type: integer
                  minimum: 1
                  maximum: 32
                  default: 1
                template:
                  type: object
                  required:
                    - spec
                  properties:
                    spec:
                      type: object
                      required:
                        - storage
                      properties:
                        partitions:
                          type: integer
                          minimum: 1
                          maximum: 1024
                          default: 1
                        storage:
                          type: object
                          required:
                            - group
                            - version
                            - name
                          properties:
                            group:
                              type: string
                            version:
                              type: string
                            kind:
                              type: string
                            namespace:
                              type: string
                            name:
                              type: string