apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storagecontrollers.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Cluster
  names:
    kind: StorageController
    listKind: StorageControllerList
    plural: storagecontrollers
    singular: storagecontroller
  versions:
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object