{{- if eq (.Values.scope | lower) "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}
rules:
  - apiGroups:
      - cloud.atomix.io
      - storage.cloud.atomix.io
    resources:
      - '*'
    verbs:
      - '*'
{{- end }}