apiVersion: cloud.atomix.io/v1beta1
kind: Database
metadata:
  name: nopaxos
spec:
  clusters: 3
  partitions: 30
  template:
    spec:
      proxy:
        image: atomix/nopaxos-proxy:latest
      backend:
        image: atomix/nopaxos-replica:latest
        replicas: 3
