apiVersion: cloud.atomix.io/v1beta1
kind: Database
metadata:
  name: nopaxos
spec:
  clusters: 3
  template:
    spec:
      partitions: 10
      proxy:
        image: atomix/nopaxos-proxy:latest
      backend:
        image: atomix/nopaxos-replica:latest
        replicas: 3
