apiVersion: storage.cloud.atomix.io/v1beta3
kind: NOPaxosStorageClass
metadata:
  name: nopaxos
spec:
  replicas: 3
---
apiVersion: cloud.atomix.io/v1beta3
kind: Database
metadata:
  name: nopaxos
spec:
  partitions: 10
  storageClass:
    group: storage.cloud.atomix.io
    version: v1beta3
    kind: NOPaxosStorage
    name: nopaxos
