apiVersion: storage.cloud.atomix.io/v1beta2
kind: NOPaxosStorage
metadata:
  name: nopaxos
spec:
  replicas: 3
---
apiVersion: cloud.atomix.io/v1beta2
kind: Database
metadata:
  name: nopaxos
spec:
  clusters: 3
  template:
    spec:
      partitions: 10
      storage:
        group: storage.cloud.atomix.io
        version: v1beta2
        kind: RaftStorage
        name: nopaxos
