apiVersion: k8s.atomix.io/v1alpha1
kind: PartitionSet
metadata:
  name: raft
spec:
  partitions: 3
  template:
    spec:
      size: 3
      raft:
        electionTimeoutMillis: 5000
        heartbeatPeriodMillis: 1000
