apiVersion: cloud.atomix.io/v1beta1
kind: Database
metadata:
  name: raft
spec:
  clusters: 3
  partitions: 30
  template:
    spec:
      backend:
        image: atomix/raft-replica:latest
        replicas: 3
        volumeMounts:
          - name: fast-disk
            path: /var/lib/atomix
      volumeClaimTemplates:
        - metadata:
            name: www
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "fast-disk"
            resources:
              requests:
                storage: 1Gi
