apiVersion: storage.cloud.atomix.io/v1beta2
kind: RaftStorage
metadata:
  name: raft
spec:
  replicas: 3
---
apiVersion: cloud.atomix.io/v1beta2
kind: Database
metadata:
  name: raft
spec:
  clusters: 3
  template:
    spec:
      partitions: 10
      storage:
        group: protocol.cloud.atomix.io
        version: v1beta2
        kind: RaftController
        name: raft
