apiVersion: k8s.atomix.io/v1alpha1
kind: PartitionGroup
metadata:
  name: raft
spec:
  partitions: 3
  partitionSize: 3
  type: raft
  image: atomix/atomix-server-raft:latest
  config: |
    electionTimeout: 5s
    heartbeatInterval: 1s