apiVersion: k8s.atomix.io/v1alpha1
kind: PartitionGroup
metadata:
  name: raft
spec:
  partitions: 3
  template:
    spec:
      size: 3
      protocol: raft
      config: |
        electionTimeout: 5s
        heartbeatInterval: 1s