apiVersion: protocol.cloud.atomix.io/v1beta1
kind: RaftProtocol
metadata:
  name: raft
spec:
  replicas: 3
---
apiVersion: cloud.atomix.io/v1beta1
kind: Database
metadata:
  name: raft
spec:
  clusters: 3
  template:
    spec:
      partitions: 10
      protocol:
        group: protocol.cloud.atomix.io
        version: v1beta1
        kind: RaftProtocol
        name: raft
