apiVersion: storage.cloud.atomix.io/v1beta3
kind: RaftStorageClass
metadata:
  name: raft
spec:
  replicas: 3
---
apiVersion: cloud.atomix.io/v1beta3
kind: Database
metadata:
  name: raft
spec:
  partitions: 10
  storageClass:
    group: storage.cloud.atomix.io
    version: v1beta3
    kind: RaftStorage
    name: raft
