apiVersion: k8s.atomix.io/v1alpha1
kind: PartitionGroup
metadata:
  name: log-group
spec:
  controller: example-atomix-controller
  version: latest
  size: 3
  partitions: 3
  log:
    storage:
      className: fast-disks