apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: partitions.k8s.atomix.io
spec:
  group: k8s.atomix.io
  names:
    kind: Partition
    listKind: PartitionList
    plural: partitions
    singular: partition
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
