apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
      - db
  versions:
    - name: v1beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - template
              properties:
                partition:
                  type: integer
                  minimum: 1
                  maximim: 1024
                  default: 1
                storage:
                  type: object
                  required:
                    - group
                    - version
                    - name
                  properties:
                    class:
                      type: string
                    group:
                      type: string
                    version:
                      type: string
                    kind:
                      type: string
                    namespace:
                      type: string
                    name:
                      type: string
            status:
              type: object
              properties:
                readyPartitions:
                  type: integer
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: partitions.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Partition
    listKind: PartitionList
    plural: partitions
    singular: partition
  versions:
    - name: v1beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                ready:
                  type: boolean
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storagecontrollers.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Cluster
  names:
    kind: StorageController
    listKind: StorageControllerList
    plural: storagecontrollers
    singular: storagecontroller
  versions:
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object