apiVersion: apiextensions.k8s.io/v1beta2
kind: CustomResourceDefinition
metadata:
  name: raft.storage.cloud.atomix.io
spec:
  group: storage.cloud.atomix.io
  names:
    kind: RaftStorage
    listKind: RaftStorageList
    plural: raftstorages
    singular: raftstorage
  scope: Namespaced
  version: v1beta2
  subresources:
    status: {}
---
apiVersion: cloud.atomix.io/v1beta2
kind: StorageController
metadata:
  name: raft
spec:
  group: storage.cloud.atomix.io
  version: v1beta2
  kind: RaftStorage
