apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: raftstorages.storage.cloud.atomix.io
spec:
  group: storage.cloud.atomix.io
  names:
    kind: RaftStorage
    listKind: RaftStorageList
    plural: raftstorages
    singular: raftstorage
  scope: Namespaced
  versions:
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
---
apiVersion: cloud.atomix.io/v1beta3
kind: StorageController
metadata:
  name: raft
spec:
  group: storage.cloud.atomix.io
  version: v1beta3
  kind: RaftStorage
