nameOverride: ""

crd:
  enabled: true

replicas: 1
image:
  repository: atomix/atomix-k8s-controller
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []
resources:
  requests:
    cpu: 0.5
    memory: 512Mi
